<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit66dee2f7dfa6ec26ef237cc2a57231bc
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FoxApp\\GitHub\\Helper\\' => 21,
            'FoxApp\\GitHub\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FoxApp\\GitHub\\Helper\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Src/GitHub/Helper',
        ),
        'FoxApp\\GitHub\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Src/GitHub',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Parsedown' => 
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FoxApp\\GitHub\\Helper\\API' => __DIR__ . '/../..' . '/Src/GitHub/Helper/API.php',
        'FoxApp\\GitHub\\Helper\\ParseCodeDown' => __DIR__ . '/../..' . '/Src/GitHub/Helper/ParseCodeDown.php',
        'FoxApp\\GitHub\\Helper\\Updater' => __DIR__ . '/../..' . '/Src/GitHub/Helper/Updater.php',
        'FoxApp\\GitHub\\Init' => __DIR__ . '/../..' . '/Src/GitHub/Init.php',
        'Parsedown' => __DIR__ . '/..' . '/erusev/parsedown/Parsedown.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit66dee2f7dfa6ec26ef237cc2a57231bc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit66dee2f7dfa6ec26ef237cc2a57231bc::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit66dee2f7dfa6ec26ef237cc2a57231bc::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit66dee2f7dfa6ec26ef237cc2a57231bc::$classMap;

        }, null, ClassLoader::class);
    }
}
