<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'FoxApp\\GitHub\\Helper\\' => array($baseDir . '/Src/GitHub/Helper'),
    'FoxApp\\GitHub\\' => array($baseDir . '/Src/GitHub'),
);
