<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'FoxApp\\GitHub\\Helper\\API' => $baseDir . '/Src/GitHub/Helper/API.php',
    'FoxApp\\GitHub\\Helper\\ParseCodeDown' => $baseDir . '/Src/GitHub/Helper/ParseCodeDown.php',
    'FoxApp\\GitHub\\Helper\\Updater' => $baseDir . '/Src/GitHub/Helper/Updater.php',
    'FoxApp\\GitHub\\Init' => $baseDir . '/Src/GitHub/Init.php',
    'Parsedown' => $vendorDir . '/erusev/parsedown/Parsedown.php',
);
